# Generated by Django 4.0.6 on 2022-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='dept',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Cs', 'Cs'), ('History', 'History'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('botany', 'botany')], max_length=10, verbose_name='Department'),
        ),
    ]
