# Generated by Django 3.1.1 on 2021-10-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('dept', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Department')),
                ('dept_code', models.CharField(max_length=100, verbose_name='Dept Code')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='workld_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('Iyr', 'First Year'), ('IIyr', 'Second Year'), ('IIIyr', 'Third Year')], max_length=8, null=True, verbose_name='Year')),
                ('clas', models.CharField(choices=[('ISem', 'First Semester'), ('IISem', 'Second Semester'), ('IIISem', 'Third Semester'), ('IVSem', 'Fourth Semester'), ('VSem', 'Fifth Semester'), ('VISem', 'sixth Semester')], max_length=8, null=True, verbose_name='Semester')),
                ('theory_workld', models.IntegerField(default='No Practicals', verbose_name='Theory Workload')),
                ('pract_workld', models.IntegerField(default='no Practicles', verbose_name='Practical Workload')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='subject_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('Iyr', 'First Year'), ('IIyr', 'Second Year'), ('IIIyr', 'Third Year')], max_length=8, null=True, verbose_name='Year')),
                ('clas', models.CharField(choices=[('ISem', 'First Semester'), ('IISem', 'Second Semester'), ('IIISem', 'Third Semester'), ('IVSem', 'Fourth Semester'), ('VSem', 'Fifth Semester'), ('VISem', 'sixth Semester')], max_length=8, null=True, verbose_name='Semester')),
                ('titlesubject', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('tot_no_hrs', models.CharField(max_length=10, verbose_name=' Allotted Tot_no_hrs')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='studprj_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Project year/Date')),
                ('project_title', models.CharField(max_length=100, verbose_name='Title of the Project')),
                ('no_of_std', models.CharField(max_length=3, verbose_name='No. of Students in the group')),
                ('name_of_std', models.CharField(max_length=100, verbose_name='Names of the Students')),
                ('remarks', models.CharField(max_length=100, verbose_name='Any Remarks')),
                ('synopsis', models.FileField(upload_to='files', verbose_name='Synopsis upload')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='stdstrength_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('Iyr', 'First Year'), ('IIyr', 'Second Year'), ('IIIyr', 'Third Year')], max_length=8, null=True, verbose_name='Year')),
                ('clas', models.CharField(choices=[('ISem', 'First Semester'), ('IISem', 'Second Semester'), ('IIISem', 'Third Semester'), ('IVSem', 'Fourth Semester'), ('VSem', 'Fifth Semester'), ('VISem', 'sixth Semester')], max_length=8, null=True, verbose_name='Semester')),
                ('no_of_stud', models.IntegerField(verbose_name='No. of Students')),
                ('combination', models.CharField(max_length=5, verbose_name='Combination')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='stdprogress_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Year Studied')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Student')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('phnum', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('joinedto', models.CharField(max_length=100, verbose_name='Name of the College joined to')),
                ('coursename', models.CharField(max_length=100, verbose_name='Name of the  Course')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='stdplacement_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Year Studied')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Student')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('phnum', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('joinedto', models.CharField(max_length=100, verbose_name='Name of the company joined to')),
                ('paypack', models.CharField(max_length=100, verbose_name='Pay package offered')),
                ('offer_letter', models.FileField(upload_to='files', verbose_name='Offer letter')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='stdperform_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('acad', 'Academic Performance'), ('non-acad', 'Non-Academic Performance')], max_length=30, null=True, verbose_name='Category type')),
                ('year', models.CharField(choices=[('Iyr', 'First Year'), ('IIyr', 'Second Year'), ('IIIyr', 'Third Year')], max_length=8, null=True, verbose_name='Year')),
                ('clas', models.CharField(choices=[('ISem', 'First Semester'), ('IISem', 'Second Semester'), ('IIISem', 'Third Semester'), ('IVSem', 'Fourth Semester'), ('VSem', 'Fifth Semester'), ('VISem', 'sixth Semester')], max_length=8, null=True, verbose_name='Semester')),
                ('combination', models.CharField(max_length=5, verbose_name='Combination')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Student')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('phnum', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('event_title', models.CharField(max_length=100, verbose_name='Title of the Event')),
                ('event_details', models.CharField(blank='True', max_length=100, null='True', verbose_name='Event details')),
                ('certif', models.FileField(upload_to='files', verbose_name='Event Certificate')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='deptproposal_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Govt', 'Govenrnment'), ('NonGovt', 'Non-Government')], max_length=30, null=True, verbose_name='Type of Agency')),
                ('year', models.DateField(verbose_name='Date Applied')),
                ('project_title', models.CharField(max_length=100, verbose_name='Title of the Project')),
                ('agency_name', models.CharField(max_length=100, verbose_name='Name of the Agency')),
                ('amount', models.CharField(max_length=100, verbose_name='Amount of the Project')),
                ('circular', models.FileField(upload_to='files', verbose_name='Advertised Circular upload')),
                ('proposal', models.FileField(upload_to='files', verbose_name='Proposal Document Upload')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='deptmeeting_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('staff_meet', 'Staff Meeting'), ('DAC', 'Department Advisory meeting'), ('AAA', 'Academic Audit meeting'), ('std_meet', 'staff Student Meeting')], max_length=30, null=True, verbose_name='Meeting category')),
                ('year', models.DateField(verbose_name='Date conducted')),
                ('agenda', models.CharField(max_length=100, verbose_name='Agenda of the Meeting')),
                ('mom', models.FileField(upload_to='files', verbose_name='Minutes of Meeting')),
                ('atr', models.FileField(upload_to='files', verbose_name='Action Taken Report')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='deptimges_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_det', models.CharField(max_length=100, verbose_name='Details of the photo')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images', verbose_name='Photos')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='deptEvent_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduct_for', models.CharField(choices=[('std', 'For Students'), ('staff', 'For Staff')], max_length=30, null=True, verbose_name='Event Conducted for')),
                ('scope', models.CharField(choices=[('Int', 'International'), ('Nation', 'National'), ('State', 'State'), ('int_class', 'Inter  Class Event'), ('int_faculty', 'Inter faculty Event'), ('int_college', 'Intercolligiate')], max_length=30, null=True, verbose_name='Type/Scope of the Event')),
                ('category', models.CharField(choices=[('FDP', 'Faculty Development Program'), ('GL', 'Guest Lecture'), ('CONF', 'Conference'), ('WORKSP', 'workshop'), ('SEMINAR', 'seminar'), ('HANDON', 'Hands on'), ('WEBINAR', 'webinar')], max_length=30, null=True, verbose_name='Event category')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('off', 'Offline')], max_length=30, null=True, verbose_name='Mode of conducting Event')),
                ('year', models.DateField(verbose_name='Date conducted')),
                ('event_Title', models.CharField(max_length=100, verbose_name='Title of the Event')),
                ('event_bro', models.FileField(upload_to='files', verbose_name='Brouchure')),
                ('event_sche', models.FileField(upload_to='files', verbose_name='Event Schedule')),
                ('event_Rpt', models.FileField(upload_to='files', verbose_name='Event Report')),
                ('event_photo', models.FileField(upload_to='files', verbose_name='Event Photos')),
                ('event_cert', models.FileField(upload_to='files', verbose_name='Event Sample Certificate')),
                ('event_approval', models.FileField(upload_to='files', verbose_name='Event Approval/Statuory letter')),
                ('event_misc', models.FileField(upload_to='files', verbose_name='Event Miscellaneous')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='depteresource_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('Iyr', 'First Year'), ('IIyr', 'Second Year'), ('IIIyr', 'Third Year')], max_length=8, null=True, verbose_name='Year')),
                ('clas', models.CharField(choices=[('ISem', 'First Semester'), ('IISem', 'Second Semester'), ('IIISem', 'Third Semester'), ('IVSem', 'Fourth Semester'), ('VSem', 'Fifth Semester'), ('VISem', 'sixth Semester')], max_length=8, null=True, verbose_name='Semester')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pract_manual', models.FileField(upload_to='files', verbose_name='Practical Manual')),
                ('e_book', models.FileField(upload_to='files', verbose_name='E-Book')),
                ('video', models.FileField(blank=True, upload_to='files', verbose_name='Video Link')),
                ('qp', models.FileField(upload_to='files', verbose_name='Question Paper')),
                ('solvedQP', models.FileField(upload_to='files', verbose_name='Solved Question Paper')),
                ('study_mat', models.FileField(upload_to='files', verbose_name='Department Notes')),
                ('others', models.FileField(upload_to='files', verbose_name='Any other relevant material')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.CreateModel(
            name='deptcomm_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_to', models.CharField(choices=[('Mgt', 'Management'), ('prin', 'Head of Institution'), ('staff', 'Among staff'), ('Univ', 'University'), ('IQAC', 'IQAC')], max_length=30, null=True, verbose_name='Communication type')),
                ('year', models.DateField(verbose_name='Date Communicated')),
                ('subject_title', models.CharField(max_length=100, verbose_name='Subject of the Communication')),
                ('letter', models.FileField(upload_to='files', verbose_name='Sent letter upload')),
                ('remark', models.CharField(max_length=100, verbose_name='Remark - follow up of the Communication')),
                ('dept', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='dept.dept')),
            ],
        ),
        migrations.AddField(
            model_name='dept',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.faculty', verbose_name='Faculty'),
        ),
    ]
