# Generated by Django 3.1.1 on 2021-10-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_no', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('year', models.CharField(blank=True, choices=[('Iyr', 'First Year'), ('IIyr', 'Second Year'), ('IIIyr', 'Third Year')], max_length=20, null=True, verbose_name='Year')),
                ('sem', models.CharField(blank=True, choices=[('ISem', 'First Semester'), ('IISem', 'Second Semester'), ('IIISem', 'Third Semester'), ('IVSem', 'Fourth Semester'), ('VSem', 'Fifth Semester'), ('VISem', 'sixth Semester')], max_length=20, null=True, verbose_name='Semester')),
                ('stream', models.CharField(blank=True, choices=[('BSc', 'BSc'), ('BCOM', 'BCOM'), ('BA', 'BA')], max_length=20, null=True, verbose_name='Stream')),
                ('comb', models.CharField(max_length=10, verbose_name='Combination/Department')),
                ('sec', models.CharField(blank=True, max_length=2, null=True, verbose_name='Section')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('is_conviner', models.BooleanField(default=False, verbose_name='Is_Conviner')),
            ],
        ),
        migrations.CreateModel(
            name='ABC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time')),
                ('title', models.CharField(max_length=30)),
                ('doc_type', models.CharField(choices=[('ARTICLE', 'ARCTICLE'), ('SPECIAL ACHIEVEMENT', 'SPECIAL ACHIEVEMENT'), ('REPORT OF AN EVENT', 'REPORT OF AN EVENT'), ('ART WORK', 'ART WORK'), ('ANY OTHER', 'ANY OTHER')], max_length=30)),
                ('doc', models.FileField(upload_to='doc')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MAGAZINEAPP.user_model')),
            ],
        ),
    ]
