# Generated by Django 3.1.1 on 2021-10-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member_model',
            fields=[
                ('org', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Organisation')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='MOM_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date conducted')),
                ('mom', models.FileField(upload_to='files', verbose_name='Minutes of meeting')),
                ('ATR', models.FileField(upload_to='files', verbose_name='Action taken Report')),
                ('org', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='Collegecells.member_model')),
            ],
        ),
        migrations.CreateModel(
            name='ClubEvent_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conduct_for', models.CharField(choices=[('std', ' Students'), ('staff', ' Staff')], max_length=30, null=True, verbose_name='Event Conducted for')),
                ('scope', models.CharField(choices=[('Int', 'International'), ('National', 'National'), ('State', 'State'), ('int_class', 'Inter  Class Event'), ('int_faculty', 'Inter faculty Event'), ('int_college', 'Intercolligiate')], max_length=30, null=True, verbose_name='Type/Scope of the Event')),
                ('category', models.CharField(choices=[('FDP', 'Faculty Development Program'), ('GL', 'Guest Lecture'), ('CONF', 'Conference'), ('WORKSP', 'workshop'), ('SEMINAR', 'seminar'), ('HANDON', 'Hands on'), ('WEBINAR', 'webinar'), ('other', 'oth')], max_length=30, null=True, verbose_name='Event category')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('off', 'Offline')], max_length=30, null=True, verbose_name='Mode of conducting Event')),
                ('year', models.DateField(verbose_name='Date conducted')),
                ('Event_Title', models.CharField(max_length=100, verbose_name='Title of the Event')),
                ('Event_bro', models.FileField(upload_to='files', verbose_name='Brouchure')),
                ('Event_sche', models.FileField(upload_to='files', verbose_name='Event Schedule')),
                ('Event_Rpt', models.FileField(upload_to='files', verbose_name='Event Report')),
                ('Event_photo', models.FileField(upload_to='files', verbose_name='Event Photos')),
                ('Event_cert', models.FileField(upload_to='files', verbose_name='Event Sample Certificate')),
                ('Event_approval', models.FileField(upload_to='files', verbose_name='Event Approval/Statuory letter')),
                ('Event_misc', models.FileField(upload_to='files', verbose_name='Event Miscellaneous')),
                ('Guest', models.CharField(max_length=30, verbose_name='Guest Name')),
                ('Guest_det', models.FileField(upload_to='files', verbose_name='Event guest Profile')),
                ('noofstd', models.CharField(max_length=10, null=True, verbose_name='Number of Students Participated')),
                ('atdlist', models.FileField(null=True, upload_to='files', verbose_name='Upload Student attendance')),
                ('org', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='Collegecells.member_model')),
            ],
        ),
        migrations.CreateModel(
            name='cellEventplan_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=15, null=True, verbose_name='Year')),
                ('Date', models.DateField(verbose_name='date of entry')),
                ('Name_ev', models.CharField(max_length=200, null=True, verbose_name='Name of the Event')),
                ('Tent_date', models.CharField(max_length=200, null=True, verbose_name='Tentative date of the Event')),
                ('Noofstd', models.CharField(max_length=200, null=True, verbose_name='Number of Students attending the Event')),
                ('Remarks', models.CharField(max_length=200, null=True, verbose_name='Remarks')),
                ('org', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='Collegecells.member_model')),
            ],
        ),
    ]
